### ISSUE TITLE
Where is documentation for labeler?

### ISSUE THREAD

**Issue by piotrkwiecinski** [gatsbyjs/peril-gatsbyjs#21]
Test ?

**Comment by SD10** [comment]
Has the peril server on Heroku been restarted?

**Comment by piotrkwiecinski** [comment]
I don't have an access to it.

**Comment by SD10** [comment]
cc @jlengstorf

**Comment by jlengstorf** [comment]
This is my bad. I pulled up Heroku and then... got distracted. 😅
