### ISSUE TITLE
Why doesn’t Peril seem to be actually adding labels?

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/peril-gatsbyjs#22]
What about now? cc @piotrkwiecinski @SD10

**Comment by jlengstorf** [comment]
Hmmm... It ran on Heroku, but nothing happened. I have to run now, but will look into adding logging later today.

**Comment by SD10** [comment]
Checklist:
- [ ] Has the peril server on Heroku been restarted?
- [ ] Does the peril app have permissions to edit issues?
- [ ] Is the peril app subscribed to issue related events?

Other thoughts:
- [We should try to update the peril instance once in awhile](https://github.com/danger/peril/blob/master/docs/updating_peril.md)
- Is there a problem with the label being found because it contains spaces?

**Comment by jlengstorf** [comment]
The labeler is being triggered without errors, so maybe we should add console logging to figure out where it dies.

![screenshot_20180804-151559](https://user-images.githubusercontent.com/163561/43680878-6940d8f2-97f9-11e8-8e14-f8f970b69e50.png)

**Comment by piotrkwiecinski** [comment]
I've started setting up peril on my own heroku account, so should be able to play around more with it tomorrow.

**Comment by jlengstorf** [comment]
I updated Peril, and I started getting errors. Still can't get console logs out of the labeler task. Posted an issue at https://github.com/danger/peril/issues/351

I'm at a bit of a loss at this point, so will wait to hear back on this issue.

A few other things got weird as well (triple-firing, for example). Not sure if that's related to the work we've been doing here or something else, but need to figure out what's happening.

**Comment by jlengstorf** [comment]
I just rolled back in hopes of restoring the working PR integration.

**Comment by jlengstorf** [comment]
So this works now, but there seems to be a problem with running multiple tasks, and I'm still hitting errors in the latest release of Peril. Once @orta is back around I'll see if I can help track down how/why that's happening.

For now, closing this.
