### ISSUE TITLE
[perilbot] Add “merge on green” support

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/peril-gatsbyjs#25]
There's a great automation that I've seen with Peril where maintainers can comment "merge on green", and Peril/Danger will auto-merge the PR as soon as all checks pass. I imagine this is pretty much a straight copy-paste from any project that supports this behavior, so let's see if we can add it in.

**Comment by SD10** [comment]
I'll take a look at the "merge on green" code and see if it still works well for Gatsby's scale. Some tweaks around who can use it or the trigger phrase may be beneficial

**Comment by thecodingaviator** [comment]
@jlengstorf I believe this has already ben implemented?

**Comment by m-allanson** [comment]
Thanks @thecodingaviator, this was done in https://github.com/gatsbyjs/peril-gatsbyjs/pull/90 🎉
