### ISSUE TITLE
[perilbot] Verify that starters and sites don't go in the wrong .yml file

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/peril-gatsbyjs#38]
Recently someone submitted a starter to the site showcase and it got merged. The site showcase is for finished sites with real content, whereas the starter showcase is for unfinished sites with dummy content. Is that the only real difference? Now I realize we probably need to carefully define the difference in our own minds.

Starter that got merged into the site showcase:
https://lisaye.netlify.com/story

PR that merged it: 
https://github.com/gatsbyjs/gatsby/pull/7709

**Comment by SD10** [comment]
@shannonbux I don't have a lot of context on the different kinds of showcases here, but is there enough metadata in the PR to determine where it belongs? 

At the very minimum, I think you could make peril leave a comment, warning the PR reviewer, whenever the `sites.yml` file is modified in a PR

**Comment by jlengstorf** [comment]
@SD10 We do require some metadata, but yeah — a warning when `sites.yml` is added is a low-hanging option that should catch most invalid submissions.

**Comment by shannonbux** [comment]
Hi @SD10 and @jlengstorf, I probably don't know enough about what kinds of metadata PR's can contain to answer for sure, but a warning could be a great idea. The warning ought to say something like: 
"Go to the URL and make sure this site matches the requirements in the Site Showcase Submission doc" 

We've gotten some submissions for things that are actually starters, so that's an example of what is difficult to catch through automation.

**Comment by jlengstorf** [comment]
Should we enforce a naming convention for starters, e.g. `gatsby-starter-*`?

**Comment by jlengstorf** [comment]
Without enforcing some kind of naming convention, this doesn't really seem feasible, especially because some sites might mention what starter they used, which could generate false positives. I'm happy to revisit this later, but for now it seems like a high-effort task that's hard for robots and easy for humans; let's just catch it in PR reviews.
