### ISSUE TITLE
[perilbot] Add link to accept invitation to the welcome comment

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/peril-gatsbyjs#42]
This is a great first issue for someone!

In the `invite-collaborator.ts` rule, we want to provide a link to accept the GitHub org invitation:
https://github.com/gatsbyjs/peril-gatsbyjs/blob/597d23d55c305618e5066a1ea4dc25cea9b164a1/rules/invite-collaborator.ts#L9

That line should be edited to say:

> 2.  **We just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. Accept the invite by visiting <https://github.com/orgs/gatsbyjs/invitation>. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

This way we don't have to worry about email invites getting swallowed by spam folders, etc. 🎉

**Comment by Yugandhartripathi** [comment]
I would like to work on this.

**Comment by bcye** [comment]
@Yugandhartripathi Oh sorry, already started working on this without commenting and didn't see your comment.

**Comment by jlengstorf** [comment]
@bcye @Yugandhartripathi I was actually able to use both of your PRs (one fixed a minor typo in the other). Thanks so much for you help!
