### ISSUE TITLE
Add all image formats supported by Sharp to image validation

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/peril-gatsbyjs#49]
Right now, the blog author validation only supports JPG images: https://github.com/gatsbyjs/peril-gatsbyjs/blob/5eb2e5fb6dd05b0886264191a04ae87b3502e667/rules/validate-yaml.ts#L6

We should actually support [all image formats supported by Sharp](http://sharp.dimens.io/en/stable/).

> This module supports reading JPEG, PNG, WebP, TIFF, GIF and SVG images.

All that's needed here is to add the allowed file extensions to the `validate-yaml.ts` section linked above!

**Comment by jwoodall3** [comment]
Hello, can I help out with this one?

**Comment by pieh** [comment]
Sure @jwoodall3! That was pretty quick :D

I just have some more info here - we probably would only want to add `.png` and maybe `.gif` to supported extensions as SVG is not supported by `gatsby-transformer-sharp` right now, TIFF doesn't actually render in browsers and WebP is not supported by all the browsers.
