### ISSUE TITLE
Duplicated labels?

### ISSUE THREAD

**Issue by LekoArts** [gatsbyjs/peril-gatsbyjs#74]
https://github.com/gatsbyjs/gatsby/issues/11471

It added two questions labels there, we wouldn't want the `question` label, would we?

**Comment by m-allanson** [comment]
Nope, it should just add one label

**Comment by m-allanson** [comment]
Looks like there’s an extra “add” on line 70 here https://github.com/gatsbyjs/peril-gatsbyjs/blob/master/rules/labeler.ts

(On my phone so cant link properly)
